
#Get the CircleCI base image
FROM cimg/base:stable-20.04 AS base

#Install Python
RUN apt install software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa -y

#Install pip

#Install RabbitMQ

#Install Celery

#Run a Celery worker

#Run RabbitMQ
